[tool.black]
line-length = 119
target-version = [
  'py39',
  'py310',
  # Because we're using an old version of black to support older python, there
  # is no explicit python version target past 3.10
]
